url: http://www.totembdg.com

title: TOTEM TOBOND

keywords: aluminium composite panel,ACP,Alucobond,Aluminum plastic panel,Aluminium sheet

description: TOTEM TOBOND aluminium composite panel and aluminum sheet factory as the famous alucobond,ACP,aluminum plastic panel and aluminium sheet supplier.

permalink: /products/:title.html

relative_permalinks: false

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  cache_assets: true
  gzip: []
